tagFormat: '${version}'
preset: conventionalcommits

branches:
  - '+([0-9])?(.{+([0-9]),x}).x'
  - master

ci: false
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits

  - - '@semantic-release/release-notes-generator'
    - preset: conventionalcommits

  - - '@semantic-release/github'
    - successComment: "This ${issue.pull_request ? 'PR is included' : 'issue has
        been resolved'} in version ${nextRelease.version} :tada:"
      labels: false
      releasedLabels: false

  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
      changelogTitle: |-
        # Changelog

        All notable changes to this project will be documented in this file.

  - - '@semantic-release/exec'
    - prepareCmd: sed -i -E s/\".*\"/\"${nextRelease.version}\"/ docmerge/__version__.py

  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
        - docmerge/__version__.py
      message: |-
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
